### PR TITLE
Fix optimize scripts loading

### PR DESCRIPTION
**Pull request by Sean1572**

### CODE REVIEW

**Comment by ntlhui** [comment]
@Sean1572 please pull changes to workflow from main to bypass HDSI website checks

**Review by ntlhui — COMMENTED** [review]
LGTM, but I don't know what to be cautious of. @ccrutchf please review and approve.

**Comment by ntlhui** [comment]
@Sean1572 @ccrutchf were there outstanding comments for this?  Or can we get this closed out?

**Comment by Sean1572** [comment]
> @Sean1572 @ccrutchf were there outstanding comments for this? Or can we get this closed out?

ready to close for me

**Review by ntlhui — APPROVED** [review]

**Review by ccrutchf — COMMENTED** [review]
As long as this doesn't break anything.  I'm happy

**Pull request merged**
